services:
    bim2sim:
        image: eliasmpjunior/bim2sim:latest
        build:
            context: ../
            dockerfile: ./docker-compose/manifests/Dockerfile
        container_name: bim2sim
        hostname: bim2sim
        volumes:
            - ../projects:/projects
            - ../bim2sim:/tmp/build/lib/bim2sim
        environment:
            - TZ=America/Sao_Paulo
        networks:
            - brasidata
        command:
            - bash
            - -c
            - |
                tail -f /dev/null

networks:
  brasidata:
    external: true
